# Generated by Django 6.0.5 on 2026-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
